Namespace prefixes can be either added or removed
SFDO-Tooling/CumulusCI pull request #1939
Opened 2020-08-12 19:15 UTC by prescod

Tests are not updated yet because I ran into a super-weird issue with the Mock library which I didn't dig into yet.

2020-10-26 16:51 UTC, davidmreed reviewed
This looks good to me. Could you also edit a mention into the Automating Data Operations document to describe the bidirectional behavior?

2020-10-26 20:14 UTC, davisagli reviewed
LGTM, aside from the doc update that David Reed asked for.

2020-10-27 00:32 UTC, davidmreed requested changes

2020-10-27 00:32 UTC, davidmreed commented on docs/bulk_data.rst
> +the same mapping file will work for orgs namespaced and unnamespaced orgs, as well as orgs with
```suggestion
the same mapping file will work for namespaced and unnamespaced orgs, as well as orgs with
```

2020-10-27 01:55 UTC, davisagli approved these changes

2020-10-27 14:34 UTC, davidmreed approved these changes

2020-10-27 15:39 UTC, merged