Add Data Synthesis cookbook.
SFDO-Tooling/CumulusCI pull request #2012
Opened 2020-09-12 01:22 UTC by prescod

Add a data synthesis cookbook to the documentation.

2020-09-14 14:33 UTC, davisagli requested changes

2020-09-14 14:33 UTC, davisagli commented on docs/cookbook.rst
> +what batch size you select, CumulusCI wll properly split your data
```suggestion
what batch size you select, CumulusCI will properly split your data
```

2020-09-14 14:33 UTC, davisagli commented on docs/cookbook.rst
> +into 10k batches for the bulk API.
```suggestion
into batches for the bulk API.
```

(there is a record count limit and a byte size limit)

2020-09-14 18:08 UTC, davisagli submitted a review, later dismissed

2020-09-14 19:24 UTC, Br4nd0R commented on docs/cookbook.rst
> +into batches for the bulk API.
🎆

2020-09-14 19:30 UTC, Br4nd0R commented on docs/cookbook.rst
> +Instad you would have 1M "partial sets".
```suggestion
Instead you would have 1M "partial sets".
```

2020-09-15 14:12 UTC, davisagli approved these changes

2020-09-15 14:12 UTC, merged