Add assign_permission_sets task
SFDO-Tooling/CumulusCI pull request #2115
Opened 2020-10-21 15:44 UTC by davidmreed

# Critical Changes

# Changes

- CumulusCI offers an `assign_permission_sets` task, which assigns one or more Permission Sets to the running user if not already assigned. This task may replace invocations of `dx`.

# Issues Closed

2020-10-21 17:20 UTC, Br4nd0R submitted a review, later dismissed
LGTM!

2020-10-21 17:49 UTC, davisagli requested changes

2020-10-21 17:49 UTC, davisagli commented on cumulusci/tasks/salesforce/users/permsets.py
> +                    WHERE Id = '{self.org_config.user_id}'"""
For scratch orgs, `user_id` is a property which does its own query of User filtering by username. Would it make more sense to just filter by username in this query?

2020-10-21 17:49 UTC, davisagli commented on cumulusci/tasks/salesforce/users/permsets.py
> +                )
Log which permsets are actually getting assigned

2020-10-21 19:33 UTC, davisagli submitted a review, later dismissed

2020-10-22 15:39 UTC, davidmreed commented
After discussion with @bethbrains added ability to target a user by alias.

2020-10-22 16:16 UTC, bethbrains commented
Hooray! Thank you!

2020-10-23 13:47 UTC, davisagli approved these changes

2020-10-23 13:47 UTC, merged