[CCI] Modified FindReplace Method to allow environment variables to b…
SFDO-Tooling/CumulusCI pull request #2146
Opened 2020-11-05 04:09 UTC by jofsky

…e passed in

# Critical Changes

# Changes

# Issues Closed

2020-11-05 14:16 UTC, davisagli commented
@jofsky what's the use case?

2020-11-05 16:30 UTC, jofsky commented
@davisagli Jenkins.

2020-11-05 20:33 UTC, davidmreed requested changes

2020-11-05 20:33 UTC, davidmreed commented on cumulusci/tasks/util.py
> +            "description": "The boolean value to treat the replace option as systems environment variable for replace. Ensure it's set in your system for best results. Defaults to False",
```suggestion
            "description": "If True, treat the value of the replace option as the name of an environment variable, and use the value of that variable as the replacement string. Defaults to False",
```

2020-11-05 20:33 UTC, davidmreed commented on cumulusci/tasks/util.py
> +                    "Please declare the replace variable in  your local environment, not found at runtime. To turn this off, set env_replace option to False."
```suggestion
                    f"The environment variable {self.options['replace']} was not found. Ensure that this value is populated or set env_replace to False."
```

2020-11-05 20:33 UTC, davidmreed commented on cumulusci/tasks/tests/test_util.py
> +    # @pytest.fixture
Remove this if we're not going to use it.

2020-11-06 15:33 UTC, davisagli requested changes

2020-11-06 15:33 UTC, davisagli commented on cumulusci/tasks/tests/test_util.py
> +        os.environ["bar"] = "bars"
Please use mock.patch.dict to make sure we only add this to the environment temporarily. We don't want to let it leak into other tests.

I see you're cleaning it up on line 161, but that won't run if the test fails before then. Using mock.patch.dict is the best way to make sure that happens. If you search for mock.patch.dict I think you'll find some other examples where we do this.

2020-11-06 15:33 UTC, davisagli commented on cumulusci/tasks/util.py
> +                self.options["replace"] = os.environ[self.options["replace"]]
Actually getting the value from the environment should be done in _run_task, not _init_options. At least with MetaDeploy, it's possible for the task to run on a completely different system than where it was initialized, and we want to use the runtime environment variables.

2020-11-06 22:05 UTC, davisagli approved these changes
Looks good to me. Before merging, can you make sure the "Changes" section of the pull request description includes a bullet point that is suitable for the release notes?

2020-11-06 22:20 UTC, jofsky commented
@davisagli Done, feel free to make comments on my note.

2020-11-06 22:23 UTC, davisagli commented
@jofsky I think I would put it like this: "The FindReplace task now has a `replace_env` option which, if true, will interpret the `replace` option as the name of an environment variable whose value should be used for the replacement." 

Whether it is secure depends on whether you use it appropriately, so let's not make that claim.

2020-11-06 22:26 UTC, jofsky commented
@davisagli Updated.

2020-11-06 22:28 UTC, davidmreed approved these changes

2020-11-06 22:28 UTC, merged