[Doc Reorg] Cheat Sheet
SFDO-Tooling/CumulusCI pull request #2320
Opened 2021-01-13 21:03 UTC by Br4nd0R

2021-01-14 01:39 UTC, davidmreed requested changes

2021-01-14 01:39 UTC, davidmreed commented on docs/cheat_sheet.rst
> +This cheatsheet is intended to provide a very brief summary of the most
```suggestion
This cheat sheet is intended to provide a very brief summary of the most
```

2021-01-14 01:39 UTC, davidmreed commented on docs/cheat_sheet.rst
> +To see what org configurations are available, run cci org list.
```suggestion
To see what org configurations are available, run ``cci org list``.
```

2021-01-14 01:39 UTC, davidmreed commented on docs/cheat_sheet.rst
> +Common examples include dev, qa, beta, and release.
```suggestion
Common examples include ``dev``, ``qa``, ``beta``, and ``release``. 
```

2021-01-14 01:39 UTC, davidmreed commented on docs/cheat_sheet.rst
> +the project's orgs directory, which determines how the scratch org is set up.
```suggestion
the project's ``orgs`` directory. The definition file determines how the scratch org is set up. 
```

2021-01-14 01:39 UTC, davidmreed commented on docs/cheat_sheet.rst
> +but you can remove names you created with cci org scratch.
```suggestion
but you can remove names you created with ``cci org scratch``.
```

2021-01-14 01:39 UTC, davidmreed commented on docs/cheat_sheet.rst
> +Connect to a persistent org (sandbox, developer edition)
```suggestion
Connect to a persistent org (sandbox, Developer Edition)
```

2021-01-14 01:39 UTC, davidmreed commented on docs/cheat_sheet.rst
> +Use the ``--sandbox`` if this is a sandbox.
```suggestion
Use the ``--sandbox`` option if this is a sandbox or any org that uses the ``test.salesforce.com`` login endpoint.
```

2021-01-14 01:39 UTC, davidmreed commented on docs/cheat_sheet.rst
> +    This section relies on concepts introduced in :ref:`key concepts` section of the documentation.
```suggestion
    This section relies on concepts introduced in the :ref:`key concepts` section of the documentation.
```

2021-01-14 01:39 UTC, davidmreed commented on docs/cheat_sheet.rst
> +This builds an unmanaged org that is designed for QA use. Should be used with an org whose configuration is ``qa``.
Let's replace all the "this"es with "This flow".

2021-01-14 01:39 UTC, davidmreed commented on docs/cheat_sheet.rst
> +    We do not recommend running an org-building-flow against the same scratch org multiple times.
```suggestion
    We do not recommend running an org-building flow against the same scratch org multiple times.
```

2021-01-14 01:39 UTC, davidmreed commented on docs/cheat_sheet.rst
> +Use ``--managed True`` if the org is managed.
This is no longer required - CCI will infer it.

2021-01-14 01:39 UTC, davidmreed commented on docs/cheat_sheet.rst
> +More Resources
We should probably just remove this section for the documentation.

2021-01-19 21:48 UTC, davisagli reviewed
I'd be interested in other perspectives, but at first glance, this is too verbose for a cheat sheet. I was thinking of something in tabular format, with a goal on the left and the related command on the right. This is not the place for explanations; it's a place to go to remind yourself of a command that you already know how to use.

2021-01-20 17:13 UTC, davidmreed commented
"Cheat sheet" is probably a misnomer. My conception for this resource (as originally written in Confluence) was an "at a glance" usage guide to basic commands intended for newer users. I think that has value, but see your point that it really _isn't_ a cheat sheet as such.

I don't think I have a really strong sense of what the users of this documentation set are most likely to need. The at-a-glance guide is responsive to a number of internal documentation pieces developed over the years, particularly by newer or infrequent CumulusCI users.

2021-01-21 23:46 UTC, Br4nd0R commented
We also have a work item slated for post-beta release to revamp this with more of a persona based approach. I definitely see your point @davisagli . Would it make sense to turn this into a "quick start" section? I'm inclined to slap this on the list of things to address after the beta release.

I feel like at some point it would behoove us to get some end user feedback as well.

2021-01-22 14:28 UTC, davisagli commented
@davidmreed @Br4nd0R Hmm, a "quick start" is different from what I was thinking -- but I certainly am not sure what is the most needed and agree that we should be guided by what users need. I'm a little worried that if we need a quick start, then we didn't do a good enough job of explaining things simply in the main documentation topics -- but again it's this challenge of how do we introduce things to new users without overwhelming, while also covering things in more depth for advanced users.

2021-01-22 15:36 UTC, davidmreed commented
I think one reason pulling this together is valuable is that we cover scratch org environment management and task and flow runs in two separate (large) sections. Those are the key players for everyday CumulusCI use.

Since none of us have a clear sense of what a user needs, why don't we ask some users? I bet Nick L. and Michael K. would be willing to offer feedback.

2021-02-24 21:13 UTC, merged