Allow num_records to be omitted in Snowfakery invocations.
SFDO-Tooling/CumulusCI pull request #2322
Opened 2021-01-16 20:56 UTC by prescod

# Changes

When invoking Snowfakery from CumulusCI, you no longer have to supply a number of records or a controlling table name. Your recipe can control the number of records created entirely.

2021-01-19 15:10 UTC, davisagli requested changes

2021-01-19 15:10 UTC, davisagli commented on docs/cookbook.rst
>  ``generator_yaml`` is a reference to your Snowkfakery recipe.
```suggestion
``generator_yaml`` is a reference to your Snowfakery recipe.
```

2021-01-19 22:02 UTC, davisagli approved these changes
Approving this, but it made me wonder -- is there anything to avoid an infinite loop if the recipe doesn't actually generate any records?

2021-01-20 22:35 UTC, merged

2021-01-21 01:45 UTC, prescod commented
@davisagli If you just asked to run the script once then it shouldn't matter whether it generated records or not (although there might be downstream bugs for this weird case).

If you asked to run the script with an SObject name specified (as was previously mandatory) then it checks to ensure that it succeeded in generating that SObject and throws an exception if not.

It's actually hard to make a no-op script by accident, by the way.