Update AUTHORS.rst
SFDO-Tooling/CumulusCI pull request #2345
Opened 2021-01-25 14:05 UTC by prescod

Update AUTHORS.rst to be more accurate.

Order is chronological by date of first contribution.

2021-01-25 16:42 UTC, davisagli reviewed
In the new docset that's in progress, we are removing this entirely so that we don't have to maintain it. It can still be found in git commit history if someone is curious. Any objection?

2021-01-25 18:30 UTC, prescod commented
I don't feel strongly one way or the other. Mildly prefer to leave it in, I guess. But not a big deal either way.

2021-01-25 18:33 UTC, davisagli commented
If we do keep it, then:
- I doubt we want to encourage reaching out to individuals, so might want to remove the emails
- There are other people who have made contributions and it feels misleading to leave them out

2021-01-25 19:22 UTC, prescod commented
I agree. 

Okay I'll just leave the decision about what to do with this PR to you, and you and Brandon, Jason or whoever can make the final decision about the new docset.

2021-01-27 16:43 UTC, Br4nd0R commented
I don't mind keeping it :) It is one more thing that will need periodic updating, but seems like a low lift.

2021-02-04 15:35 UTC, jstvz commented
If we keep it, we can update CONTRIBUTING to tell new contributors to add themselves if they want to be included. This would shift the maintenance burden to contributors and allow them to decide how they'd like to be included (e.g., full name vs github username).

2021-02-18 18:28 UTC, codexmarcel approved these changes

2021-02-18 19:11 UTC, davisagli requested changes
I would like to remove the emails. We want to point people to our official channels for support, not encourage reaching out to individuals.

2021-02-19 02:58 UTC, Br4nd0R submitted a review, later dismissed

2021-02-19 14:40 UTC, davisagli commented on AUTHORS.rst
> +* Marcel Pufal
```suggestion
* Marcel Pufal
* David Ray
```

2021-02-19 14:40 UTC, davisagli approved these changes

2021-02-19 15:11 UTC, merged