New task in layouts.py - Add Lightning Action to Page Layouts
SFDO-Tooling/CumulusCI pull request #2548
Opened 2021-04-13 22:48 UTC by ClayTomerlin

# Critical Changes

# Changes

# Issues Closed

2021-04-14 17:17 UTC, jstvz commented
@ClayTomerlin Moving this PR to ready to review to match the WI.

2021-04-20 06:48 UTC, jstvz requested changes
Thanks! I've requested a few tweaks.

2021-04-20 06:48 UTC, jstvz commented on cumulusci/tasks/metadata_etl/tests/test_layouts.py
> +            *tuple([n for n in range(1, mock_action_list_size + 1)]),
```suggestion
            *range(1, mock_action_list_size + 1),
```

2021-04-20 06:48 UTC, jstvz commented on cumulusci/tasks/metadata_etl/tests/test_layouts.py
> +        ), "The transformed actual_metadata should match our expected_metadata, with the new action item placed first"
I recommend moving the message from the assertion to the comment above.

2021-04-20 06:48 UTC, jstvz commented on cumulusci/tasks/metadata_etl/tests/test_layouts.py
> +        ), "AddRecordPlatformActionListItem should return None when actionListItem already exists in metadata"
I recommend moving this message from the assertion to the comment above.

2021-04-20 06:48 UTC, jstvz commented on cumulusci/tasks/metadata_etl/tests/test_layouts.py
> +            *tuple([n for n in range(mock_action_list_size)]),
`range` is also a sequence, so you can unpack it here:
```suggestion
            *range(1, mock_action_list_size + 1),
```

2021-04-20 06:48 UTC, jstvz commented on cumulusci/tasks/metadata_etl/layouts.py
> +        )
Consider instead:

```suggestion
        self._place_first = process_bool_arg(
            self.options.get("place_first") or False
        )
```

2021-04-20 06:48 UTC, jstvz commented on cumulusci/tasks/metadata_etl/layouts.py
> +            "description": "When 'True' the specified Record Platform Action List Item will be inserted before any existing on the layout. Default is 'False'",
I would tweak this to be consistent with the other options:
```suggestion
            "description": "When 'True' the specified Record platformActionListItem will be inserted before any existing on the layout. Default is 'False'",
```

2021-04-21 03:00 UTC, ClayTomerlin commented on cumulusci/tasks/metadata_etl/tests/test_layouts.py
> +            *tuple([n for n in range(1, mock_action_list_size + 1)]),
Ah, I was overthinking it a bit here

2021-04-21 03:08 UTC, ClayTomerlin commented
@jstvz  Changes complete - thank you for the guidance and tips, let me know if I missed anything

2021-04-22 14:00 UTC, jstvz approved these changes

2021-04-22 14:01 UTC, merged