[CCI] First commit of working push_api version refactor.
SFDO-Tooling/CumulusCI pull request #2607
Opened 2021-05-10 21:15 UTC by jofsky

# Critical Changes

# Changes

# Issues Closed

2021-06-16 16:40 UTC, jofsky commented
LOL @jstvz I thought I had tagged you for review on this like a month ago.

2021-06-29 06:28 UTC, jstvz requested changes
Thanks for getting this working. There's a couple of fixes needed, as well as some additional test coverage.

---
<details>
<summary>Smoke testing</summary>

Running against a production packaging org with:
```console
$ cctr push_sandbox --org packaging --version 1.12 --start_time 2021-06-29T23:55 --dry_run True
[...]
2021-06-28 19:27:20: Selected 62 orgs. Skipping actual creation of the PackagePushRequest because the dry_run flag is on.
```

returned 62 orgs while the UI returned 60. The two extra orgs had Beta versions installed:

| MajorVersion | MinorVersion | PatchVersion | BuildNumber | Name                   | ReleaseState |
|--------------|--------------|--------------|-------------|------------------------|--------------|
| 1            | 0            | 0            | 4           | Automated beta release | Beta         |
| 1            | 14           | 0            | 1           | Automated beta release | Beta         |

This is okay (the current behavior), but I wanted to take note of it here. (There's an even bigger difference between the task and UI when production orgs are included, but that's mostly down to a known platform issue).

`min_version`: 
The wrong parameter name is being passed to `get_older_released_version_objs()`, but if I fix that and re-run the above task with `--min_version 1.7` the task returns 54 orgs, which matches the query results and push upgrade UI.

</details>


<details>
<summary>Unit tests</summary>


The fact that unit tests are passing implies that they may not be testing the tasks' behavior correctly. There's only one test in `test_push_tasks.py` that includes the `min_version` option:

https://github.com/SFDO-Tooling/CumulusCI/blob/06779d94cd5a59b2f77652f43b809daaad7bf3a3/cumulusci/tasks/push/tests/test_push_tasks.py#L445-L463

Because the we're only testing the exception there are several uncovered lines below the `get_older_released_version_objs()` call in `SchedulePushOrgQuery._get_Orgs`.

</details>

2021-06-29 06:28 UTC, jstvz commented on cumulusci/tasks/push/tests/test_push_api.py
> +        MetadataPackageVersion(
A list comprehension could be more succinct.

2021-06-29 06:28 UTC, jstvz commented on cumulusci/tasks/push/tests/test_push_api.py
> +            build="1",
Would you mind adding some additional versions that use the other version numbers (`minor`, `patch`, etc.)?

2021-07-06 21:02 UTC, jstvz requested changes
Almost there, just need to fix an unused import.

Fine to leave test coverage for a separate PR, but we definitely need to revisit this.

2021-07-06 23:22 UTC, jstvz approved these changes

2021-07-06 23:24 UTC, merged