Verbose mode for flow info
SFDO-Tooling/CumulusCI pull request #2845
Opened 2021-09-01 16:01 UTC by bethbrains

# Critical Changes

# Changes
- Adding `--verbose` to `cci flow info` will output all flow options defined.

# Issues Closed

2021-09-01 20:10 UTC, jstvz requested changes
🚀

---
You've got some test failures to resolve here. You'll also need to add coverage for your conditionals by adding tests to test_flowrunner.py: https://github.com/SFDO-Tooling/CumulusCI/blob/d535ae6c51fccce7995be348bf66fd81f1562e37/cumulusci/core/tests/test_flowrunner.py#L146-L162

2021-09-01 20:10 UTC, jstvz commented on cumulusci/core/flowrunner.py
> +                        options_info += f"\n{padding}{padding} {option}: {value}"
These lines aren't covered by a test.

2021-09-01 20:10 UTC, jstvz commented on cumulusci/core/flowrunner.py
> +                lines.append(options_info)
This branch is uncovered.

2021-09-01 21:24 UTC, jstvz requested changes
Sorry, I linked to the wrong example in my original review. I meant to reference this test that covers the `for_docs` parameter in test_flowrunner: https://github.com/SFDO-Tooling/CumulusCI/blob/d535ae6c51fccce7995be348bf66fd81f1562e37/cumulusci/core/tests/test_flowrunner.py#L180-L194

As a general rule, we test each module's behavior in its corresponding test module. We'd want to also verify that the option's behavior is correct there.

2021-09-02 13:27 UTC, davisagli reviewed
I tried it out, code and tests lgtm. One tiny suggestion.

2021-09-09 21:23 UTC, bethbrains commented
[W-8887744](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000096YIXIA2/view)

2021-09-09 21:49 UTC, Br4nd0R approved these changes
This lgtm, nice work @bethbrains!

2021-09-09 21:52 UTC, merged

2021-09-09 21:52 UTC, davisagli commented
@bethbrains please update the suggested release note in the PR description since we ended up not exposing the `--verbose` flag

2021-09-15 16:23 UTC, jstvz commented
Closes #2835