Rename config files to match current coding standards
SFDO-Tooling/CumulusCI pull request #3028
Opened 2022-01-07 20:04 UTC by prescod

Rename config files to:

1. Reflect current naming standards.
2. Be easier to disambiguate from their same-named classes, for mocking and importing purposes

2022-01-20 23:36 UTC, davidmreed requested changes
The code looks good, but this change breaks MetaCI, so I'm going to put a "request changes" until we sort that out.

Integration tests:
- [x] MetaDeploy
- [ ] MetaCI
- [ ] Metecho

2022-01-28 05:03 UTC, prescod commented
@davidmreed The MetaCI change seems to be as shallow as we'd expect, based on my local testing. We can triple-check by making a dev release and linking to that on CI and staging environments.

2022-01-28 15:45 UTC, davisagli commented on cumulusci/version.txt
> +3.51.1.dev1
This should be 3.52.0.dev0 -- 3.51.1.dev1 comes before 3.51.1 the way that PyPI sorts version numbers.

2022-01-28 15:52 UTC, davisagli commented on cumulusci/core/config/__init__.py
> +
Why did you move this one? I guess as long as there aren't import cycle problems it's fine, but ScratchOrgConfig extends SfdxOrgConfig so it made sense to me for them to be listed in the previous order.

2022-01-28 20:03 UTC, prescod commented
`isort` does that @David Glick ***@***.***>

On Fri, Jan 28, 2022 at 7:52 AM David Glick ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In cumulusci/core/config/__init__.py
> <https://github.com/SFDO-Tooling/CumulusCI/pull/3028#discussion_r794626006>
> :
>
> >
>  # inherit from BaseTaskFlowConfig
>  from cumulusci.core.config.project_config import BaseProjectConfig
>
> +# inherit from SfdxOrgConfig
> +from cumulusci.core.config.scratch_org_config import ScratchOrgConfig
> +
>
> Why did you move this one? I guess as long as there aren't import cycle
> problems it's fine, but ScratchOrgConfig extends SfdxOrgConfig so it made
> sense to me for them to be listed in the previous order.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SFDO-Tooling/CumulusCI/pull/3028#pullrequestreview-866327002>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAFMS2ZLQJBDFP35EINCGDUYK3URANCNFSM5LPRHBXA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-01-28 20:05 UTC, davisagli commented
eek, we probably need to disable isort for `__init__.py` files

2022-01-28 20:46 UTC, prescod commented
@davisagli It looks like we do have such a setting but my editor doesn't know about it.

In-file declarations are probably more reliable?

So 

1. do you want me to "unsort" this particular file?

2. do you want us to add isort disabling comments too each __init__.py file?

2022-01-28 20:48 UTC, davisagli commented
@prescod I don't think any immediate action is required as long as it's still possible to run cci commands without hitting ImportErrors. But adding the comment to disable isort in `__init__.py` files that have convenience imports sounds like a good idea to me.

2022-01-31 15:15 UTC, davisagli commented
I believe this is simply waiting for a fix in version.txt and final approval by @davidmreed

2022-01-31 19:58 UTC, prescod commented
Okay thanks @davisagli . Updated to 3.52.0.dev0 . Although I am unclear what happens if we get the sort order wrong for dev releases. Nothing wrong with getting it "right" of course, just curious if there is anything that happens if you get it wrong.

@davidmreed Ready for your re-review.

2022-01-31 20:05 UTC, davisagli commented
@prescod Quite possible it wouldn't actually matter in practice, but I can think of 2 situations where it might. It would make a difference in whether the new dev release gets installed when someone pip installs cumulusci with the `--pre` flag but no specific version specified. It would also interfere with a downstream dependency specifying the dev release as a minimum required version (e.g. `cumulusci>=3.51.0.dev0` would allow 3.51.0 but `cumulusci>=3.52.0.dev0` wouldn't. I think)

2022-01-31 22:15 UTC, davidmreed approved these changes

2022-02-01 01:58 UTC, merged