Warn Windows users when long paths are not enabled
SFDO-Tooling/CumulusCI pull request #3069
Opened 2022-02-11 00:29 UTC by jstvz

This PR adds a utility function to report whether the environment supports long pathnames and warn the user if they are not. This function is called from task/flow run on each invocation.

Notes:
- Weird: There's also an import in the function itself because the `winreg` module will only be present on windows.
- Perf ↓: Adds ~400ms per run.

# Critical Changes

# Changes

# Issues Closed

2022-02-11 14:52 UTC, davisagli commented on cumulusci/cli/utils.py
> +    print("foo")
👀

2022-02-11 16:39 UTC, prescod commented
Given the perf cost:

1. Should we run this code once per hour like the version check?
2. Should we run it only until longpaths are enabled? Then assume they will remain enabled?
3. Should we run it 100% of the time in cci error and cci version contexts?

2022-02-11 21:40 UTC, jstvz commented on cumulusci/cli/utils.py
> +    print("foo")
🥸

2022-02-21 23:57 UTC, davidmreed requested changes
Looks great - just flagging a couple lines in tests that look like they're false-positiving.

2022-02-21 23:57 UTC, davidmreed commented on cumulusci/cli/tests/test_utils.py
> +    "LongPathsEnabled" in query_value.cal_args.args
```suggestion
    assert "LongPathsEnabled" in query_value.cal_args.args
```

2022-02-21 23:57 UTC, davidmreed commented on cumulusci/cli/tests/test_utils.py
> +
Missing call to method under test?

2022-02-22 00:43 UTC, davidmreed approved these changes

2022-02-22 00:43 UTC, merged