Mask GitHub tokens in cci service info output
SFDO-Tooling/CumulusCI pull request #3295
Opened 2022-07-20 16:10 UTC by bethbrains

2022-07-20 20:36 UTC, davidmreed commented on cumulusci/cli/service.py
> +                    (v[:5] + (len(v[5:]) * "*") if k == "token" else str(v)),
Hard-coding the name here will cure the immediate P1 bug, but it's fragile and breaks the abstraction for Services. 

I suggest instead that we get the project config (`runtime.project_config or runtime.universal_config`). Then we can get the service definition (see `cumulusci/cumulusci.yml` around line 1306 and `service.py` around line 27-68) and find the `attribute` for this key. 

We can add to each attribute a new k/v pair in YAML: `secure: bool`.

Then we mask any attribute marked secure, which should include the GitHub token but also any future service with the same issue.

2022-07-20 20:37 UTC, davidmreed commented on cumulusci/cli/service.py
> +                    (v[:5] + (len(v[5:]) * "*") if k == "token" else str(v)),
OK, you pushed a commit doing essentially this within seconds of me submitting the review. Nice, @bethbrains

2022-07-20 20:41 UTC, davisagli commented
Check what the similar setting for task options is called. IIRC it was sensitive rather than secure

David

> On Jul 20, 2022, at 1:37 PM, David Reed ***@***.***> wrote:
> 
> ﻿
> @davidmreed commented on this pull request.
> 
> In cumulusci/cli/service.py:
> 
> > @@ -283,7 +283,10 @@ def service_info(runtime, service_type, service_name, plain):
>          service_data = [["Key", "Value"]]
>          service_data.extend(
>              [
> -                [click.style(k, bold=True), str(v)]
> +                [
> +                    click.style(k, bold=True),
> +                    (v[:5] + (len(v[5:]) * "*") if k == "token" else str(v)),
> OK, you pushed a commit doing essentially this within seconds of me submitting the review. Nice, @bethbrains
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.

2022-07-20 20:42 UTC, davidmreed approved these changes

2022-07-21 00:18 UTC, jstvz requested changes
Run `make schema` to update the JSON schema and resolve the test failures.

2022-07-21 18:55 UTC, jstvz commented on cumulusci/core/github.py
> +        )
```suggestion
        options["scopes"] = ", ".join(sorted(get_oauth_scopes(repo_response)))
```

2022-07-22 16:52 UTC, jstvz approved these changes

2022-07-22 17:57 UTC, merged