Added claifying documentation around GES configuration
SFDO-Tooling/CumulusCI pull request #3362
Opened 2022-09-19 18:24 UTC by davidjray

Small Teak to documentation

2022-09-19 20:28 UTC, davidjray commented
It's worth noting that validation already exists when configuring new `github_enterprise` services to prevent duplicate `repo_domain`

2022-09-20 02:08 UTC, jstvz approved these changes
Some copyedits and tweaks.

---

Now that I'm reading this, I'm having second thoughts about calling it `repo_domain`, as it's really more of a `server_domain` or a `ges_domain`. 😬

2022-09-20 02:08 UTC, jstvz commented on docs/get-started.md
> +The GitHub Enterprise Server Support feature only allows one `github_enterprise` service to be configured per repository domain. This means the access token you are using must have permission to acce
```suggestion
The GitHub Enterprise Server service only allows one `github_enterprise` service to be configured per server domain. This means the access token you are using must have permission to access all required resources at a given repository location.
```

2022-09-20 15:55 UTC, prescod requested changes
I'm moving this out of Approved status given James' suggestions.

2022-09-22 23:42 UTC, davidjray commented
I actually like the idea of renaming `repo_domain` to `server_domain`, it is much clearer.

2022-09-26 18:26 UTC, jstvz approved these changes

2022-09-26 23:06 UTC, merged