Update transforms.py
SFDO-Tooling/CumulusCI pull request #3625
Opened 2023-07-18 20:32 UTC by GeekStewie

- Updated FindReplaceIdSpec to get the first column of the select statement instead of ID

2023-07-31 21:38 UTC, davidmreed requested changes

2023-07-31 21:38 UTC, davidmreed commented on cumulusci/core/source_transforms/transforms.py
>  import functools
Can you also update the tests?

2023-07-31 21:39 UTC, davidmreed commented
@GeekStewie My apologies, I thought that I had submitted a review for you and it was sitting in Pending state.

2026-05-26 23:36 UTC, jstvz commented
Thanks for the contribution and apologies for the long delay. CumulusCI is experimenting with a long-running `dev` branch to improve development velocity on v5 work; `main` continues to receive v4.x patches. This PR predates that change and is now stale enough that we are closing it to reduce queue noise.

If the underlying issue still affects you, we would welcome a fresh PR against the appropriate branch (`main` for a v4.x bug fix, `dev` for v5-only work).

2026-05-26 23:36 UTC, closed without merging