Description for not_found error
SFDO-Tooling/CumulusCI pull request #3659
Opened 2023-09-21 05:39 UTC by lakshmi2506

2023-09-21 05:54 UTC, lakshmi2506 commented
Hi @davidmreed 

Added a descriptive message for the not_found error while creating a scratch org. It is due to not hitting the correct endpoint or doesn't have access to the API version you are using.

Please review the code 
Thank you

2023-09-27 16:47 UTC, davidmreed requested changes
Nice work, @lakshmi2506! Just a couple of requests from me.

2023-09-27 16:47 UTC, davidmreed commented on cumulusci/core/config/scratch_org_config.py
> +                Output = json.loads(stdout)
Variable names in Python typically use "`lower_snake_case`".

```suggestion
                output = json.loads(stdout)
```

2023-09-27 16:47 UTC, davidmreed commented on cumulusci/core/config/scratch_org_config.py
> +                        "Check the API Version or endpoint you are interacting"
```suggestion
                        "The Salesforce CLI was unable to create a scratch org. Ensure you are connected using a valid API version on an active Dev Hub."
```

2023-09-29 00:16 UTC, jofsky approved these changes

2023-09-29 01:34 UTC, merged