added_clear_error
SFDO-Tooling/CumulusCI pull request #3676
Opened 2023-10-12 07:48 UTC by lakshmi2506

2023-10-12 08:06 UTC, lakshmi2506 commented
Hi @davidmreed @jkasturi-sf 
 
 I have added a clear error message when the create_package_version is run against a persistent orgs.
 Please review the code
 Thank you

2023-10-24 22:48 UTC, jstvz requested changes

2023-10-24 22:48 UTC, jstvz commented on cumulusci/tasks/create_package_version.py
> +                "Org doesn't contain a config_file. It's a persistent org like Devhub or Developer Edition org"
While this error message is better, I think we can still improve it. In general, we want to explain what happened and why, and help the user fix it. With that in mind, how about something like this?:
```suggestion
                "Target org scratch org definition file missing. Persistent orgs (e.g., Dev Hub) can't be used for 2GP package uploads."
```

In addition, the ACs for this story include task documentation. You can add`task_docs` to the class (see [this example](https://github.com/SFDO-Tooling/CumulusCI/blob/210f78cccb744b7cc9a1fbf19c2cf50805c0f47c/cumulusci/tasks/bulkdata/generate_mapping.py#L14-L34)) to let users know what the org is for when they run `cci task info`. Something like:
```python
task_docs = """
    Facilitates the upload of 2GP (second-generation packaging)
    package versions using CumulusCI.

    The target org is used both for looking up dependency package IDs and
    configuring the build org during the package upload. Ensure the specified
    org is a scratch org with the correct configuration for these purposes.
    """
```

2023-10-24 22:48 UTC, jstvz commented on cumulusci/tasks/tests/test_create_package_version.py
> +
Dead code should be removed.

2023-10-24 22:48 UTC, jstvz commented on cumulusci/tasks/tests/conftest.py
> +    return persistent_org_config
Are you sure we need this in a fixture if we're only using it in a single test?

2023-10-24 22:48 UTC, jstvz commented on cumulusci/tasks/tests/test_create_package_version.py
> +            match="Org doesn't contain a config_file. It's a persistent org like Devhub or Developer Edition org",
Consider moving the error message to a constant (see [here](https://github.com/SFDO-Tooling/CumulusCI/blob/520b51128c7702a374da9a8838f38890082fd3de/cumulusci/tasks/marketing_cloud/deploy.py#L37)) and importing it ([example](https://github.com/SFDO-Tooling/CumulusCI/blob/520b51128c7702a374da9a8838f38890082fd3de/cumulusci/tasks/marketing_cloud/tests/test_deploy.py#L18)). This makes it easier to change in one place and helps keep the code clean and simple.

2023-10-26 22:15 UTC, jstvz reviewed
LGTM, just a few tweaks.

2023-10-26 22:15 UTC, jstvz commented on cumulusci/tasks/create_package_version.py
> +"""
Minor typo and simplification:
```suggestion
PERSISTENT_ORG_ERROR = """
Target org scratch org definition file missing. Persistent orgs like a Dev Hub can't be used for 2GP package uploads.
"""
```

2023-10-26 22:15 UTC, jstvz commented on cumulusci/tasks/create_package_version.py
> +            raise TaskOptionsError(PERSISTANT_ORG_ERROR)
```suggestion
            raise TaskOptionsError(PERSISTENT_ORG_ERROR)
```

2023-10-26 22:15 UTC, jstvz commented on cumulusci/tasks/tests/test_create_package_version.py
> +    PERSISTANT_ORG_ERROR,
```suggestion
    PERSISTENT_ORG_ERROR,
```

2023-10-26 22:15 UTC, jstvz commented on cumulusci/tasks/tests/test_create_package_version.py
> +            task.__init__
This can be removed:

```suggestion
```

Note that the`__init__` method is the class constructor and is called during initialization.

2023-10-26 22:16 UTC, jstvz submitted a review, later dismissed

2023-10-30 07:04 UTC, lakshmi2506 commented
Hi @jstvz 

Made the required spelling change to pass the checks.

Please review the request 
Thank you

2023-10-30 22:14 UTC, jstvz approved these changes

2023-10-31 06:46 UTC, jkasturi-sf approved these changes
Looks good

2023-10-31 08:51 UTC, merged