W-15805907: assign_permission_set_licenses accepts the api_names in either developerName or the PermissionSetLicenseKey
SFDO-Tooling/CumulusCI pull request #3798
Opened 2024-06-07 07:10 UTC by lakshmi2506

To handle the compatibility issues and ensure smooth functionality for both `get_available_permission_set_licenses` and `assign_permission_set_licenses`, you can make the following adjustments:

1. **Revert `get_available_permission_set_licenses` to Return `PermissionSetLicenseKey`:**
   - This will maintain backward compatibility.

2. **Update `assign_permission_set_licenses` to Accept Both `DeveloperName` and `PermissionSetLicenseKey`:**
   - Modify the function to handle input as either `DeveloperName` or `PermissionSetLicenseKey`, ensuring it can correctly interpret and process both formats. This adjustment will resolve issues with names like `alpha.beta` where the `DeveloperName` is `alpha_beta`.

2024-06-07 07:12 UTC, lakshmi2506 commented
Hi @jkasturi-sf @jstvz @vsbharath 

Please review the PR

Thank you

2024-06-12 21:41 UTC, jstvz requested changes
Change requested: Please update the `task_docs` to mention that `api_names` can contain `DeveloperName` or `PermissionSetLicenseKey`. Other comments optional.

2024-06-12 21:41 UTC, jstvz commented on cumulusci/tasks/salesforce/users/permsets.py
> +                f"SELECT Id,{permission_field} FROM {self.permission_name} WHERE {permission_field} IN ('{api_names}')"
Have you considered combining these into a single query?

2024-06-12 21:41 UTC, jstvz commented on cumulusci/tasks/salesforce/users/permsets.py
> +                p["Id"]: p[permission_field] for p in perms["records"]
This function ultimately queries both `DeveloperName` and `PermissionSetLicenseKey`, but it ends up potentially clobbering the `DeveloperName` with `PermissionSetLicenseKey`. That's inconsistent, but probably fine if displaying the actual found name is important for debugging.

2024-06-13 06:02 UTC, lakshmi2506 commented
Hi @jstvz 

Combined the queries into one, updated the task docs.

Please review the PR
Thank you

2024-06-14 18:47 UTC, jstvz approved these changes

2024-06-14 19:37 UTC, merged