@W-17366392: Fix Omnistudio issues for the compatibility with sfdx
SFDO-Tooling/CumulusCI pull request #3855
Opened 2024-12-06 15:53 UTC by lakshmi2506

2024-12-06 16:01 UTC, jkasturi-sf submitted a review, later dismissed
VBT tool is not supporting SF cli. So reverting back to SFDX Cli

2024-12-06 17:45 UTC, jstvz requested changes
@lakshmi2506 this PR changes from `sf` back to `sfdx`. Since CumulusCI already uses `sf`, going back might cause problems for people who depend on the newer commands. Could you please share the exact errors you saw when using `sf`?

The Vlocity team [mentioned](https://github.com/vlocityinc/vlocity_build/issues/687) that using the `useSfCli` setting and the `1.17.10` release might fix these issues. Have we tried that yet?

Could we discuss:

- The exact error messages you encountered when using sf?
- The results of testing `useSfCli` with version `1.17.10`?

We should have a plan for what happens when we run into commands that only work with `sfdx`. For example, could we make the build fail with a clear error message, rather than quietly switching back and forth between `sf` and `sfdx`?

2024-12-10 23:56 UTC, vsbharath requested changes

2024-12-10 23:56 UTC, vsbharath commented on cumulusci/tasks/vlocity/vlocity.py
> +            "force:auth:accesstoken:store",
Try this 
           ```
 "sf",
            "org", "login", "access-token",
            "--alias",
            f"{VBT_SF_ALIAS}",
            "--instance-url",
            f"{instance_url}",
```

2024-12-11 00:03 UTC, vsbharath commented on cumulusci/tasks/vlocity/vlocity.py
>              "--no-prompt",
```suggestion
            "sf",
            "org", "login", "access-token",
```

2024-12-11 03:31 UTC, lakshmi2506 commented on cumulusci/tasks/vlocity/vlocity.py
>              "--no-prompt",
Thanks 🙇🏻‍♀️   @vsbharath, that worked.

2024-12-11 05:35 UTC, vsbharath approved these changes

2024-12-11 05:46 UTC, vsbharath approved these changes

2024-12-11 17:51 UTC, jstvz approved these changes

2024-12-11 19:08 UTC, merged